name: Premshay
favicon: null
layout_spectrum: 0.09825012390501797
typography_spectrum: 0.1058956766501069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7861110053490847
  lightness: 0.4767483319155872
  saturation: 0.7916406015865505
  rhythmicContrast: 0.5143984172027558
purpose: []
